### ISSUE TITLE
Cannot return as T1 as result is T0

### ISSUE THREAD

**Issue by JarrodJ83** [Liversage/OneOf.Serialization.SystemTextJson#1]
Trying out your package and getting the following error. Not sure why it is trying to serialize as T1 because the object is T0:

<img width="173" alt="image" src="https://github.com/Liversage/OneOf.Serialization.SystemTextJson/assets/248166/869da054-0db1-4c7e-9061-5bb23e1f2351">

```
   at OneOf.OneOf`2.get_AsT1()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
```

Any help would be appreciated! Thanks!

**Comment by Liversage** [comment]
@JarrodJ83 Can you provide more information? I need to be able to reproduce the issue to investigate it. Stack traces are useful but I in the one provided here I don't see any code from this library.
